<?php

namespace Annuaire\RestoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

   public function getSelectList(){
		$qb = $this->createQueryBuilder('post'); // On filtre sur l'attribut publication
		// Et on retourne simplement le QueryBuilder, et non la Query, attention
		return $qb;
	}
	
		
}
