services:
    sonata.admin.post:
        class: Annuaire\RestoBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - Annuaire\RestoBundle\Entity\Restaurant
            - ~
        calls:
            - [ setTranslationDomain, [AnnuaireRestoBundle]]