parameters:
#    annuaire_user.example.class: Annuaire\UserBundle\Example

services:
#    annuaire_user.example:
#        class: %annuaire_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
